=begin
#Permit.io API

#Fullstack Authorization as a Service

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PDPDecisionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PDPDecisionsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PDPDecisionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PDPDecisionsApi' do
    it 'should create an instance of PDPDecisionsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PDPDecisionsApi)
    end
  end

  # unit tests for get_decision_logs
  # List PDP Decisions
  # Get a list of all PDP decisions filtered by users, timestamp, decision, etc.
  # @param pdp_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :users List of user IDs to filter by
  # @option opts [Boolean] :approved Filter by approved decisions
  # @option opts [Array<String>] :resources Filter by resources
  # @option opts [Integer] :timestamp_from Filter by timestamp from
  # @option opts [Integer] :timestamp_to Filter by timestamp to
  # @option opts [Integer] :skip Skip first n results
  # @option opts [Integer] :limit Limit to n results
  # @option opts [String] :x_organization_id The id of the active organization you want to query on
  # @return [DecisionLogResponseList]
  describe 'get_decision_logs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
