=begin
#Permit.io API

#Fullstack Authorization as a Service

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PermissionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PermissionsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PermissionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PermissionsApi' do
    it 'should create an instance of PermissionsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PermissionsApi)
    end
  end

  # unit tests for assign_permissions_to_role
  # Assign Permissions To Role
  # Assign permissions to a given role.
  # @param role_id 
  # @param permission_selection 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_organization_id The id of the active organization you want to query on
  # @return [nil]
  describe 'assign_permissions_to_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_role_permissions
  # List Role Permissions
  # Get a list of permissions assigned to a given role.
  # @param role_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :skip Skip first n results
  # @option opts [Integer] :limit Limit to n results
  # @option opts [String] :x_organization_id The id of the active organization you want to query on
  # @return [PermissionList]
  describe 'list_role_permissions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_permissions_from_role
  # Remove Permissions From Role
  # Remove permissions from a given role.
  # @param role_id 
  # @param permission_selection 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_organization_id The id of the active organization you want to query on
  # @return [nil]
  describe 'remove_permissions_from_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
