=begin
#Permit.io API

#Fullstack Authorization as a Service

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::DecisionLogGrantPermissions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::DecisionLogGrantPermissions do
  let(:instance) { OpenapiClient::DecisionLogGrantPermissions.new }

  describe 'test an instance of DecisionLogGrantPermissions' do
    it 'should create an instance of DecisionLogGrantPermissions' do
      expect(instance).to be_instance_of(OpenapiClient::DecisionLogGrantPermissions)
    end
  end
  describe 'test attribute "permission"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "granting_role"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
